{% set version = '0.2.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-anomalydetection
  version: {{ version|replace("-", "_") }}

source:
  fn: anomalyDetection_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/anomalyDetection_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/anomalyDetection/anomalyDetection_{{ version }}.tar.gz
  sha256: 5f0248d2e8fb03f8be54bc2ad76c11fe9f7bc481d1234c53e83dedf4fb4a3529

build:
  number: 0
  # r-tidyverse is not available under windows
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-rcolorbrewer
    - r-caret
    - r-dplyr
    - r-gmp
    - r-gplots
    - r-magrittr
    - r-matrixstats
    - r-plyr
    - r-purrr
    - r-qdaptools
    - r-tibble
    - r-tidyverse
  run:
    - r-base
    - r-mass
    - r-rcolorbrewer
    - r-caret
    - r-dplyr
    - r-gmp
    - r-gplots
    - r-magrittr
    - r-matrixstats
    - r-plyr
    - r-purrr
    - r-qdaptools
    - r-tibble
    - r-tidyverse

test:
  commands:
    - $R -e "library('anomalyDetection')"  # [not win]
    - "\"%R%\" -e \"library('anomalyDetection')\""  # [win]

about:
  home: https://github.com/bradleyboehmke/anomalyDetection
  license: GPL (>= 2)
  summary: |
    Implements procedures to aid in detecting network log anomalies. By combining various
    multivariate analytic approaches relevant to network anomaly detection, it provides
    cyber analysts efficient means to detect suspected anomalies requiring further evaluation.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
