# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DNWf3mQWE/H2DLaBchIte1Vt+7Chpt+HBK+liFeSJN4kdensPb5BvYc9Tt68mPRF7IACsTi3Ogfm6QMyBN4NVzweTMN7IBX2LV1EgZYNMoDnvSFNgUPlbSOjsp76QGSKXkQdCoMUW5j2xh7tcn+m+FRjKBRxU+Gpy02Y3KwPpYGgi2zltKenF7gNsgXIUUSI86bbKq9bwG+rzPMylzUq+Gg6FXwJJESAxpLpvi8yR6SCEwFCHxpuu8vYjdf57WUVFeC9rhMM4ZGU40A0JgzJxK+gv+qtCm1weu5Opomjm8sWwiX/sihp70LEo3rvfasSrGG5m0FR+Z4Y/JOVtWxMeGz/8WpDgZBDRH8Eq0RvHdr6wSJqIWFfJB+ySo1gg+ROseOJArfOwjOwJwxBnLP5g8RxbLoVQfxmammCJn9UMDM2wuOw7TaSClhyM9zA5k3geQ63Ts0Jx6GMHJaeBekVd4v92PWBNSnysOwTf3uXF5Gh/IGIkYhzCohvPLHL7IbsjGR70tKr+ouYH3QGtwuVFyAMIatoHuftRkDZvc8oMfZA/22WFFJs3xLv9uFa/eMvGNZyr8aVRxrOwmUFTq42yHSzmZITR1VVbrUCSzEy12a3+xdPmzu8qZdPe1k8GfPf4TcNMj+MvdAzx8UzqX7msKFhR3F2wcj+Qj4kDRxNFdk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
