travis:
  secure:
    BINSTAR_TOKEN: DNWf3mQWE/H2DLaBchIte1Vt+7Chpt+HBK+liFeSJN4kdensPb5BvYc9Tt68mPRF7IACsTi3Ogfm6QMyBN4NVzweTMN7IBX2LV1EgZYNMoDnvSFNgUPlbSOjsp76QGSKXkQdCoMUW5j2xh7tcn+m+FRjKBRxU+Gpy02Y3KwPpYGgi2zltKenF7gNsgXIUUSI86bbKq9bwG+rzPMylzUq+Gg6FXwJJESAxpLpvi8yR6SCEwFCHxpuu8vYjdf57WUVFeC9rhMM4ZGU40A0JgzJxK+gv+qtCm1weu5Opomjm8sWwiX/sihp70LEo3rvfasSrGG5m0FR+Z4Y/JOVtWxMeGz/8WpDgZBDRH8Eq0RvHdr6wSJqIWFfJB+ySo1gg+ROseOJArfOwjOwJwxBnLP5g8RxbLoVQfxmammCJn9UMDM2wuOw7TaSClhyM9zA5k3geQ63Ts0Jx6GMHJaeBekVd4v92PWBNSnysOwTf3uXF5Gh/IGIkYhzCohvPLHL7IbsjGR70tKr+ouYH3QGtwuVFyAMIatoHuftRkDZvc8oMfZA/22WFFJs3xLv9uFa/eMvGNZyr8aVRxrOwmUFTq42yHSzmZITR1VVbrUCSzEy12a3+xdPmzu8qZdPe1k8GfPf4TcNMj+MvdAzx8UzqX7msKFhR3F2wcj+Qj4kDRxNFdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
